### ISSUE TITLE
busy on windows ?

### ISSUE THREAD

**Issue by rusco** [tejzpr/busy#2]
On my win10 machine I get this message while building:

# github.com/go-vgo/robotgo
In file included from ./bitmap/../base/str_io_c.h:2:0,
                 from ./bitmap/goBitmap.h:17,
                 from ..\pkg\mod\github.com\go-vgo\robotgo@v0.93.1\robotgo.go:45:
./bitmap/../base/zlib_util_c.h:2:18: fatal error: zlib.h: No such file or directory
compilation terminated.

Is Windows supported ? Any further requirements ? I have gcc installed.

**Comment by tejzpr** [comment]
I have created a release with executable for windows. Building busy in windows requires Mingw64 or  [TDM-GCC](https://jmeubank.github.io/tdm-gcc/download/) along with [Zlib](https://sourceforge.net/projects/mingw-w64/files/External%20binary%20packages%20%28Win64%20hosted%29/Binaries%20%2864-bit%29/zlib-1.2.5-bin-x64.zip/download) then 
copy _\zlib\bin to \TDM\bin
copy \zlib\include to \TDM\include
copy \zlib\lib to \TDM\lib
